### ISSUE TITLE
PLY read doesn't work for headers with \r\n

### ISSUE THREAD

**Issue by yonkahlon** [Danny02/OpenCTM#6]
Simple bug - line 307 in tools\rply\rply.c:

```
if (strcmp(magic, "ply\n")) {
        fclose(fp);
        error_cb("Not a PLY file. Expected magic number 'ply\\n'");
        return NULL;
    }
```

On Windows PCL is saving the ply header using \r\n, i.e:

```
ply\r\n
format ascii 1.0\r\n
... ect
```

I've forked to fix it on my side, but maybe you can fix it here?

**Comment by yonkahlon** [comment]
Wasn't as simple as I thought...

Also need to modify the following function:

`static int ply_read_word(p_ply ply)`

if the ply header looks like this:

```
ply\r\n
format binary_little_endian 1.0\r\n
comment PCL generated\r\n
element vertex 1548\r\n
property float x\r\n
property float y\r\n
property float z\r\n
property uchar red\r\n
property uchar green\r\n
property uchar blue\r\n
property float nx\r\n
property float ny\r\n
property float nz\r\n
property float curvature\r\n
element face 2699\r\n
property list uchar int vertex_indices\r\n
end_header\r\n
```
ply_read_word will read: `end_header\n` leaving behind the `\r` which I think is subsequently used when reading the ply binary data (this is unconfirmed though, but it does produce an invalid mesh error)

 Maybe I can make a pull request to submit my solution?

**Comment by JuliaWinchester** [comment]
Was there ever any progress on this? I'm facing the same issue.

**Comment by yonkahlon** [comment]
@JuliaWinchester: I've just commit my fix to a fork of this repo: https://github.com/yonkahlon/OpenCTM

**Comment by JuliaWinchester** [comment]
@yonkahlon Thanks for this! It's much appreciated.

**Comment by Danny02** [comment]
thx for fixing this problem, I will merge your fix
